(function() {var implementors = {};
implementors["fluence_client"] = [{"text":"impl Unpin for Transport","synthetic":true,"types":[]},{"text":"impl Unpin for Client","synthetic":true,"types":[]},{"text":"impl Unpin for ClientCommand","synthetic":true,"types":[]},{"text":"impl Unpin for ClientEvent","synthetic":true,"types":[]}];
implementors["fluence_libp2p"] = [{"text":"impl Unpin for RandomPeerId","synthetic":true,"types":[]}];
implementors["host_closure"] = [{"text":"impl Unpin for Args","synthetic":true,"types":[]},{"text":"impl Unpin for ArgsError","synthetic":true,"types":[]}];
implementors["particle_actors"] = [{"text":"impl Unpin for VmPoolConfig","synthetic":true,"types":[]},{"text":"impl Unpin for PlumberEvent","synthetic":true,"types":[]},{"text":"impl Unpin for Plumber","synthetic":true,"types":[]}];
implementors["particle_behaviour"] = [{"text":"impl Unpin for ParticleBehaviour","synthetic":true,"types":[]},{"text":"impl Unpin for ParticleConfig","synthetic":true,"types":[]}];
implementors["particle_closures"] = [{"text":"impl Unpin for BehaviourMailboxApi","synthetic":true,"types":[]},{"text":"impl Unpin for HostClosures","synthetic":true,"types":[]},{"text":"impl Unpin for BuiltinCommand","synthetic":true,"types":[]},{"text":"impl Unpin for Mailbox","synthetic":true,"types":[]}];
implementors["particle_dht"] = [{"text":"impl Unpin for DHTEvent","synthetic":true,"types":[]},{"text":"impl Unpin for ParticleDHT","synthetic":true,"types":[]},{"text":"impl Unpin for DHTConfig","synthetic":true,"types":[]},{"text":"impl Unpin for ResolveError","synthetic":true,"types":[]},{"text":"impl Unpin for ResolveErrorKind","synthetic":true,"types":[]},{"text":"impl Unpin for NeighborhoodError","synthetic":true,"types":[]}];
implementors["particle_modules"] = [{"text":"impl Unpin for Blueprint","synthetic":true,"types":[]},{"text":"impl Unpin for ModuleError","synthetic":true,"types":[]}];
implementors["particle_protocol"] = [{"text":"impl Unpin for ProtocolMessage","synthetic":true,"types":[]},{"text":"impl Unpin for ProtocolConfig","synthetic":true,"types":[]},{"text":"impl Unpin for Particle","synthetic":true,"types":[]}];
implementors["particle_providers"] = [{"text":"impl Unpin for Provider","synthetic":true,"types":[]},{"text":"impl Unpin for ProviderRepository","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Unpin for ProviderError&lt;'a&gt;","synthetic":true,"types":[]}];
implementors["particle_server"] = [{"text":"impl Unpin for Server","synthetic":true,"types":[]},{"text":"impl Unpin for ServerBehaviour","synthetic":true,"types":[]}];
implementors["particle_services"] = [{"text":"impl Unpin for ParticleAppServices","synthetic":true,"types":[]},{"text":"impl Unpin for ServicesConfig","synthetic":true,"types":[]}];
implementors["server_config"] = [{"text":"impl Unpin for AppServicesConfig","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Unpin for BehaviourConfig&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Unpin for BootstrapConfig","synthetic":true,"types":[]},{"text":"impl Unpin for FluenceConfig","synthetic":true,"types":[]},{"text":"impl Unpin for ServerConfig","synthetic":true,"types":[]},{"text":"impl Unpin for KademliaConfig","synthetic":true,"types":[]}];
implementors["test_utils"] = [{"text":"impl Unpin for ConnectedClient","synthetic":true,"types":[]},{"text":"impl Unpin for Instruction","synthetic":true,"types":[]},{"text":"impl Unpin for CreatedSwarm","synthetic":true,"types":[]},{"text":"impl Unpin for Trust","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Unpin for SwarmConfig&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Unpin for CreatedService","synthetic":true,"types":[]}];
implementors["trust_graph"] = [{"text":"impl Unpin for Certificate","synthetic":true,"types":[]},{"text":"impl Unpin for KeyPair","synthetic":true,"types":[]},{"text":"impl Unpin for PublicKeyHashable","synthetic":true,"types":[]},{"text":"impl Unpin for Trust","synthetic":true,"types":[]},{"text":"impl Unpin for TrustGraph","synthetic":true,"types":[]}];
implementors["waiting_queues"] = [{"text":"impl Unpin for Enqueued","synthetic":true,"types":[]},{"text":"impl&lt;K, V&gt; Unpin for WaitingQueues&lt;K, V&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;K: Unpin,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: Unpin,&nbsp;</span>","synthetic":true,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()